Repository Sfrisio/chref, pull requests merged in 2022-11, with the labels that each got.

#6 Documentation and Recursion
  README.md
  VERSION
  build/build.go
  main.go
Labels: documentation, enhancement

#9 Update README.md
  README.md
Labels: documentation, enhancement

#10 Documentation
  README.md
Labels: documentation

#13 Feat/build scripts
  scripts/binary-builder.sh
Labels: enhancement

#16 Manpage source
  manpages/chref.1
Labels: documentation
